.TH infinitemariobros 7
.SH NAME
infinitemariobros \-A more compatible version of Infinite Mario.
.SH SYNOPSIS
.B infinitemariobros
.TP
.SH DESCRIPTION
.B infinitemariobros
A more compatible version of Infinite Mario
.SH OPTIONS
.TP
f  Full screen mode
Example:

infintiemariobros f
.SH DISCLAIMER
use at your own risk.
.SH AUTHORS 
Written by cflewis
